# -*- coding: utf-8 -*-
"""final_hr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oJ9sEc4J1MRgfnDaxL2sZdv3CfHEoU6L

# **Step 1:Cleaning (Redundant Columns, Duplicates, Attrition Conversion, Label Encoding)**

## Load and check on data
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("HR-Employee-Attrition.csv")

df

df.info()

df.isnull().sum()

df.describe()

df_processed = df.copy()

"""##Deleting redundant columns"""

columns_to_drop = ["EmployeeCount", "StandardHours", "Over18", "EmployeeNumber"]
df_processed = df_processed.drop(columns=columns_to_drop, errors="ignore")
print(f"Dropped redundant columns: {columns_to_drop}")

"""## Dropping duplicates


"""

initial_rows = df_processed.shape[0]
df_processed.drop_duplicates(inplace=True)
if df_processed.shape[0] < initial_rows:
    print(f"Dropped {initial_rows - df_processed.shape[0]} duplicate rows.")
else:
    print("No duplicate rows found.")

"""## Convert "Attrition" to numerical (Yes=1, No=0)"""

df_processed["Attrition"] = df_processed["Attrition"].map({"Yes": 1, "No": 0})
print("Converted 'Attrition' to numerical values: Yes=1, No=0")

"""## Apply Label Encoding to other categorical columns"""

categorical_cols = df_processed.select_dtypes(include=["object"]).columns
for col in categorical_cols:
    le = LabelEncoder()
    df_processed[col] = le.fit_transform(df_processed[col])
print(f"Applied Label Encoding to categorical columns: {list(categorical_cols)}")

print("\n")

print("Data after initial cleaning and encoding:")
print(df_processed.info())

df_after_cleaning = df_processed.copy()

import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")

columns = df_after_cleaning.columns

n_cols = 4
n_rows = (len(columns) + n_cols - 1) // n_cols

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 4))

axes = axes.flatten()

for i, col in enumerate(columns):
    sns.boxplot(y=df_after_cleaning[col], ax=axes[i])
    axes[i].set_title(f'Boxplot of {col}')
    axes[i].set_ylabel('')

for j in range(i + 1, len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

df_processed.shape

"""## Define features (X) and target (y)

"""

X = df_processed.drop("Attrition", axis=1)
y = df_processed["Attrition"]

"""## Remove (Attrition') from numerical_cols , as it's now the target variable

"""

numerical_cols = df_processed.select_dtypes(exclude=['object']).columns.tolist()
numerical_cols.remove('Attrition')

"""## Split the data into training and testing sets"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

df_processed.shape

"""## 4. Perform feature scaling (StandardScaler)

"""

scaler = StandardScaler()
X_train[numerical_cols] = scaler.fit_transform(X_train[numerical_cols])
X_test[numerical_cols] = scaler.transform(X_test[numerical_cols])

X_train.to_csv("X_train.csv", index=False)
X_test.to_csv("X_test.csv", index=False)
y_train.to_csv("y_train.csv", index=False)
y_test.to_csv("y_test.csv", index=False)

"""# **Step 2: Implementation of models**

## Load preprocessed data
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install catboost

import pandas as pd
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from catboost import CatBoostClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, silhouette_score

X_train = pd.read_csv("X_train.csv")
X_test = pd.read_csv("X_test.csv")
y_train = pd.read_csv("y_train.csv").values.ravel()
y_test = pd.read_csv("y_test.csv").values.ravel()

results = {}

def evaluate_classification_model(model, name):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, zero_division=0)
    recall = recall_score(y_test, y_pred, zero_division=0)
    f1 = f1_score(y_test, y_pred, zero_division=0)
    results[name] = {
        "Accuracy": accuracy,
        "Precision": precision,
        "Recall": recall,
        "F1-Score": f1
    }
    print(f"{name} - Accuracy: {accuracy:.4f}, Precision: {precision:.4f}, Recall: {recall:.4f}, F1-Score: {f1:.4f}")

"""## 1. Linear Regression"""

print("\n--- Linear Regression ---")
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)

y_pred_lin_reg = (lin_reg.predict(X_test) > 0.5).astype(int)
accuracy_lin_reg = accuracy_score(y_test, y_pred_lin_reg)
precision_lin_reg = precision_score(y_test, y_pred_lin_reg, zero_division=0)
recall_lin_reg = recall_score(y_test, y_pred_lin_reg, zero_division=0)
f1_lin_reg = f1_score(y_test, y_pred_lin_reg, zero_division=0)

results["Linear Regression"] = {
    "Accuracy": accuracy_lin_reg,
    "Precision": precision_lin_reg,
    "Recall": recall_lin_reg,
    "F1-Score": f1_lin_reg
}
print(f"Linear Regression - Accuracy: {accuracy_lin_reg:.4f}, Precision: {precision_lin_reg:.4f}, Recall: {recall_lin_reg:.4f}, F1-Score: {f1_lin_reg:.4f}")

"""## 2. Logistic Regression

"""

print("\n--- Logistic Regression ---")
evaluate_classification_model(LogisticRegression(max_iter=1000, solver='liblinear'), "Logistic Regression")

"""## 3. Decision Trees

"""

print("\n--- Decision Trees ---")
evaluate_classification_model(DecisionTreeClassifier(random_state=42), "Decision Trees")

"""## 4. Random Forest

"""

print("\n--- Random Forest ---")
evaluate_classification_model(RandomForestClassifier(random_state=42), "Random Forest")

"""## 5. Support Vector Machine (SVM)

"""

print("\n--- Support Vector Machine (SVM) ---")
evaluate_classification_model(SVC(random_state=42), "Support Vector Machine (SVM)")

"""## 6. K-Nearest Neighbor (KNN)"""

print("\n--- K-Nearest Neighbor (KNN) ---")
evaluate_classification_model(KNeighborsClassifier(), "K-Nearest Neighbor (KNN)")

"""## 7. Naive Bayes

"""

print("\n--- Naive Bayes ---")
evaluate_classification_model(GaussianNB(), "Naive Bayes")

"""## 8. Gradient Boosting

"""

print("\n--- Gradient Boosting (XGBoost) ---")
evaluate_classification_model(XGBClassifier(random_state=42, use_label_encoder=False, eval_metric='logloss'), "XGBoost")

print("\n")

print("\n--- Gradient Boosting (LightGBM) ---")
evaluate_classification_model(LGBMClassifier(random_state=42), "LightGBM")

print("\n")

print("\n--- Gradient Boosting (CatBoost) ---")
evaluate_classification_model(CatBoostClassifier(random_state=42, verbose=0), "CatBoost")

"""
# **Step 3: Models summary**"""

import pandas as pd

results_df = pd.DataFrame(results).T

results_df = results_df.round(4)

print("\n--- Model Performance Summary ---")
print(results_df)

best_model_name = results_df["Accuracy"].idxmax()
best_model_score = results_df.loc[best_model_name, "Accuracy"]

print(f"\n\n Best Model: {best_model_name} with Accuracy = {best_model_score:.4f}")

from IPython.display import display
display(results_df)